inherit: 
    - wandb.yaml

model:
    family: SoftmaxEncoder
    n_embd: 6
    n_layer: 1
    n_head: 1
    n_dims: 3
    n_point: 50
    n_positions: 101

training:
    task: semi_classification
    task_kwargs: {"sparsity": 3}
    data: onehot
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 10000
    train_steps: 200001
    curriculum:
        points:
            start: 50
            end: 50
            inc: 2
            interval: 2000
        dims:
            start: 3
            end: 3
            inc: 1
            interval: 2000


out_dir: ../models/semi_supervised

wandb:
    name: "semi_supervised_points_50_layers_1_dim_3"
